#!/usr/bin/python

'''
usage: newsfeed.py [-h] [-t] [-c]

Get your news without having to leave the terminal!

optional arguments:
  -h, --help       show this help message and exit
  -t , --top       Display top <N> stories
  -c , --country   Filter news by <COUNTRY>
  -k , --keyword   Filter news for a specified <KEYWORD>
  -C , --category  Filter news within a specified <CATEGORY>
  -s , --sources   Specify a <SOURCE> for news. I.E. cnn, bbc-news

'''

from os import sys
from helpers import formatter
from helpers import commandParser
from helpers.urlBuilder import URL
from helpers.newsAPI import NewsAPI

def main(argv):

    query = commandParser.parse(argv)

    response = NewsAPI.request(query)

    if response['status'] == 'ok':
        formatter.displayNews(response['articles'])
    else:
        formatter.displayError(response)

if __name__ == '__main__':
    main(sys.argv[1:])
