#!/usr/bin/python
'''
usage: newsfeed.py [-h] [-t] [-c]

Get your news without having to leave the terminal!

optional arguments:
  -h, --help       show this help message and exit
  -t , --top       Display top <N> stories
  -c , --country   Filter news by <COUNTRY>

'''

from os import sys
from helpers import commandParser
from helpers.urlBuilder import URL

def main(argv):

    NEWS_API      = "https://newsapi.org/v2/"
    TOP_HEADLINES = "top-headlines?"

    aliases = { 'keyword' : 'q', 'top' : 'pageSize' }

    query = commandParser.parse(argv)
    url = URL(NEWS_API, TOP_HEADLINES, query=query, aliases=aliases)

    print(query)
    print(url.url)

if __name__ == '__main__':
    main(sys.argv[1:])
